services:
  - type: web
    name: parkisense
    runtime: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements_render.txt"
    startCommand: "gunicorn --workers=2 --timeout=120 --bind=0.0.0.0:$PORT main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: parkisense_secret_render_2024
      - key: MONGODB_URI
        value: mongodb+srv://abhishekkurimeti97_db_user:E1lOIPImeOw43Izw@cluster0.gege15n.mongodb.net/parkisense?retryWrites=true&w=majority
      - key: ENCRYPTION_KEY
        value: opVjAjT3z__mi9-j0dWS6idv5GqHFuk7CFQvuwB5Gio=
